version: '3.2'

services:
  app:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8080"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
