swagger: "2.0"
info:
  version: "0.0.1"
  title: Catcher Service
# during dev, should point to your local machine
host: localhost:8080
# basePath prefixes all resource paths 
basePath: /api/v1/
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /catchers/{id}:
    # binds a127 app logic to a route
    x-swagger-router-controller: registration
    get:
      description: Returns Catcher to the caller
      # used as the method name of the controller
      operationId: getCatcherById
      parameters:
        - in: path
          name: id
          description: Catcher Id
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/SuccessResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /catchers/email/{email}:
    # binds a127 app logic to a route
    x-swagger-router-controller: registration
    get:
      description: Returns Catcher to the caller
      # used as the method name of the controller
      operationId: getCatcherByEmail
      parameters:
        - in: path
          name: email
          description: Catcher Email
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/SuccessResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /catchers:
    x-swagger-router-controller: registration
    post:
      summary: add a catcher
      operationId: addCatcher
      description: Add a catcher to the system
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: catcher
        required: true
        description: Add Catcher
        schema:
          $ref: '#/definitions/Catcher'
      responses:
        201:
          description: catcher added
          schema:
            # a pointer to a definition
            $ref: "#/definitions/SuccessResponse"
        400:
          description: invalid input, object invalid
          schema:
            # a pointer to a definition
            $ref: "#/definitions/ErrorResponse"
        409:
          description: an existing catcher already exists
          schema:
            # a pointer to a definition
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  Catcher:
    type: object
    required:
    - firstName
    - lastName
    - email
    - phone
    - address
    - postcode
    properties:
      firstName:
        type: string
        minLength: 1
        example: Sherlock
      lastName:
        type: string
        minLength: 1
        example: Holmes
      email:
        type: string
        format: email
        example: sherlock.holmes@detective.com
      phone:
        type: string
        minLength: 11
        maxLength: 11
        example: 0123456789
      address:
        type: string
        minLength: 1
        example: 221B Baker Steeet, London
      postcode:
        type: string
        minLength: 6
        maxLength: 7
        example: SW19 01B
  SuccessResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
