swagger: "2.0"
info:
  version: "0.0.1"
  title: Catcher Service
# during dev, should point to your local machine
host: localhost:8080
# basePath prefixes all resource paths 
basePath: /api/v1/
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /ping:
    # binds a127 app logic to a route
    x-swagger-router-controller: serviceCheck
    get:
      description: Returns pong to the caller
      # used as the method name of the controller
      operationId: getPong
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/SuccessResponse"
  /confirm:
    # binds a127 app logic to a route
    x-swagger-router-controller: serviceCheck
    get:
      description: Confirm user and redirect to url
      # used as the method name of the controller
      operationId: confirmUser
      parameters:
        - in: query
          name: clientId
          description: client Id
          required: true
          type: string
        - in: query
          name: userName
          description: User Name
          required: true
          type: string
        - in: query
          name: confirmationCode
          description: Confirmation Code
          required: true
          type: string
        - in: query
          name: redirectUrl
          description: Redirect Url
          required: true
          type: string
      responses:
        "302":
          description: Success, redirect to Url
          schema:
            # a pointer to a definition
            $ref: "#/definitions/SuccessResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /users/email/{email}:
    # binds a127 app logic to a route
    x-swagger-router-controller: registration
    get:
      description: Returns User (Catcher/Subscriber) info to the caller
      # used as the method name of the controller
      operationId: getUserByEmail
      parameters:
        - in: path
          name: email
          description: User Email
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/SuccessResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /catchers/{uid}:
    # binds a127 app logic to a route
    x-swagger-router-controller: registration
    get:
      description: Returns Catcher info to the caller
      # used as the method name of the controller
      operationId: getCatcherById
      parameters:
        - in: path
          name: uid
          description: Catcher Unique Id
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/SuccessResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /catchers/email/{email}:
    # binds a127 app logic to a route
    x-swagger-router-controller: registration
    get:
      description: Returns Catcher info to the caller
      # used as the method name of the controller
      operationId: getCatcherByEmail
      parameters:
        - in: path
          name: email
          description: Catcher Email
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/SuccessResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /catchers:
    x-swagger-router-controller: registration
    post:
      summary: Add a catcher
      operationId: addCatcher
      description: Add a catcher
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: catcher
        required: true
        description: Add Catcher
        schema:
          $ref: '#/definitions/AddCatcher'
      responses:
        201:
          description: Catcher added
          schema:
            # a pointer to a definition
            $ref: "#/definitions/SuccessResponse"
        400:
          description: Invalid input, object invalid
          schema:
            # a pointer to a definition
            $ref: "#/definitions/ErrorResponse"
        409:
          description: An existing catcher already exists
          schema:
            # a pointer to a definition
            $ref: "#/definitions/ErrorResponse"
    
    put:
      summary: Update an existing catcher
      operationId: updateCatcher
      description: Update an existing catcher
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: catcher
        required: true
        description: Update Catcher
        schema:
          $ref: '#/definitions/UpdateCatcher'
      responses:
        204:
          description: Catcher updated
          schema:
            # a pointer to a definition
            $ref: "#/definitions/SuccessResponse"
        400:
          description: Invalid catcher id provided
          schema:
            # a pointer to a definition
            $ref: "#/definitions/ErrorResponse"
  /catchers/{uid}/subscribers:
    # binds a127 app logic to a route
    x-swagger-router-controller: registration
    get:
      description: Returns subscribers allocated to the catcher
      # used as the method name of the controller
      operationId: getSubscribersAllocatedToCatcher
      parameters:
        - in: path
          name: uid
          description: Catcher Unique Id
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/SuccessResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  AddCatcher:
    type: object
    required:
    - firstName
    - lastName
    - email
    - phone
    - address
    - city
    - postcode
    properties:
      firstName:
        type: string
        minLength: 1
        example: Sherlock
      lastName:
        type: string
        minLength: 1
        example: Holmes
      email:
        type: string
        format: email
        example: sherlock.holmes@detective.com
      phone:
        type: string
        minLength: 11
        maxLength: 11
        example: 0123456789
      address:
        type: string
        minLength: 1
        example: 221B Baker Steeet
      city:
        type: string
        minLength: 1
        example: London
      county:
        type: string
        example: London Borough
      postcode:
        type: string
        minLength: 6
        maxLength: 9
        description: Postcode without spaces
        example: SW19 01B
  UpdateCatcher:
    type: object
    required:
    - id
    - email
    properties:
      id:
        type: string
        minLength: 12
        example: CRS7GA000001
      firstName:
        type: string
        minLength: 1
        example: Sherlock
      lastName:
        type: string
        minLength: 1
        example: Holmes
      email:
        type: string
        format: email
        example: sherlock.holmes@detective.com
      phone:
        type: string
        minLength: 11
        maxLength: 11
        example: 0123456789
      address:
        type: string
        minLength: 1
        example: 221B Baker Steeet
      city:
        type: string
        minLength: 1
        example: London
      county:
        type: string
        example: Londng Borough
      postcode:
        type: string
        minLength: 6
        maxLength: 9
        description: Postcode without spaces
        example: SW19 01B
      isActive:
        type: boolean
        description: Catcher status (active/inactive)
        example: true
  SuccessResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
